language: scala
jdk: oraclejdk7
scala:
  - 2.10.5
  - 2.11.6

script:
  - "sbt ++$TRAVIS_SCALA_VERSION test:compile"
  - "sbt ++$TRAVIS_SCALA_VERSION it:compile"
  - "sbt ++$TRAVIS_SCALA_VERSION test"

